/*
 * JS for xxx generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return 'b572e3eb-742e-4282-8fcc-ec2f1e9e6ff1';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "xxx",
    "location": "xxx.html"
}, {
    "name": "Screen1",
    "location": "Screen1.html"
}];

xxx_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'CustomComponent1_341': 'xxx_CustomComponent1_341',
        'CustomComponent1_341_mobilecollapsblock_219': 'xxx_CustomComponent1_341_mobilecollapsblock_219',
        'CustomComponent1_341_mobilecollapsblockheader_220': 'xxx_CustomComponent1_341_mobilecollapsblockheader_220',
        'CustomComponent1_341_mobilecollapsblockcontent_221': 'xxx_CustomComponent1_341_mobilecollapsblockcontent_221',
        'CustomComponent1_341_mobilelabel_222': 'xxx_CustomComponent1_341_mobilelabel_222',
        'CustomComponent1_341_mobilelabel_223': 'xxx_CustomComponent1_341_mobilelabel_223',
        'CustomComponent1_341_mobilecollapsblock_224': 'xxx_CustomComponent1_341_mobilecollapsblock_224',
        'CustomComponent1_341_mobilecollapsblockheader_225': 'xxx_CustomComponent1_341_mobilecollapsblockheader_225',
        'CustomComponent1_341_mobilecollapsblockcontent_226': 'xxx_CustomComponent1_341_mobilecollapsblockcontent_226',
        'CustomComponent1_341_mobilelabel_227': 'xxx_CustomComponent1_341_mobilelabel_227',
        'CustomComponent1_341_mobilelabel_228': 'xxx_CustomComponent1_341_mobilelabel_228',
        'CustomComponent1_341_mobilelabel_230': 'xxx_CustomComponent1_341_mobilelabel_230',
        'CustomComponent1_341_mobilelabel_233': 'xxx_CustomComponent1_341_mobilelabel_233',
        'CustomComponent1_341_mobilelabel_234': 'xxx_CustomComponent1_341_mobilelabel_234',
        'CustomComponent1_341_mobilelabel_235': 'xxx_CustomComponent1_341_mobilelabel_235',
        'CustomComponent1_341_mobilelabel_236': 'xxx_CustomComponent1_341_mobilelabel_236',
        'CustomComponent1_341_mobilecollapsblock_237': 'xxx_CustomComponent1_341_mobilecollapsblock_237',
        'CustomComponent1_341_mobilecollapsblockheader_238': 'xxx_CustomComponent1_341_mobilecollapsblockheader_238',
        'CustomComponent1_341_mobilecollapsblockcontent_239': 'xxx_CustomComponent1_341_mobilecollapsblockcontent_239',
        'CustomComponent1_341_mobilelabel_240': 'xxx_CustomComponent1_341_mobilelabel_240',
        'CustomComponent1_341_mobilelabel_241': 'xxx_CustomComponent1_341_mobilelabel_241',
        'CustomComponent1_341_mobilelabel_242': 'xxx_CustomComponent1_341_mobilelabel_242',
        'CustomComponent1_341_mobilelabel_243': 'xxx_CustomComponent1_341_mobilelabel_243',
        'CustomComponent1_341_mobilelabel_244': 'xxx_CustomComponent1_341_mobilelabel_244',
        'CustomComponent1_341_mobilelabel_245': 'xxx_CustomComponent1_341_mobilelabel_245',
        'CustomComponent1_341_mobilelabel_246': 'xxx_CustomComponent1_341_mobilelabel_246',
        'CustomComponent1_341_mobilelabel_247': 'xxx_CustomComponent1_341_mobilelabel_247',
        'CustomComponent1_341_mobilelabel_248': 'xxx_CustomComponent1_341_mobilelabel_248',
        'CustomComponent1_341_mobilelabel_249': 'xxx_CustomComponent1_341_mobilelabel_249',
        'CustomComponent1_341_mobilecollapsblock_250': 'xxx_CustomComponent1_341_mobilecollapsblock_250',
        'CustomComponent1_341_mobilecollapsblockheader_251': 'xxx_CustomComponent1_341_mobilecollapsblockheader_251',
        'CustomComponent1_341_mobilecollapsblockcontent_252': 'xxx_CustomComponent1_341_mobilecollapsblockcontent_252',
        'CustomComponent1_341_mobilelabel_253': 'xxx_CustomComponent1_341_mobilelabel_253',
        'CustomComponent1_341_mobilelabel_254': 'xxx_CustomComponent1_341_mobilelabel_254',
        'CustomComponent1_341_mobilelabel_255': 'xxx_CustomComponent1_341_mobilelabel_255',
        'CustomComponent1_341_mobilelabel_256': 'xxx_CustomComponent1_341_mobilelabel_256',
        'CustomComponent1_341_mobilelabel_257': 'xxx_CustomComponent1_341_mobilelabel_257',
        'CustomComponent1_341_mobilelabel_258': 'xxx_CustomComponent1_341_mobilelabel_258',
        'CustomComponent1_341_mobilelabel_259': 'xxx_CustomComponent1_341_mobilelabel_259',
        'CustomComponent1_341_mobilelabel_260': 'xxx_CustomComponent1_341_mobilelabel_260',
        'mobilecollapsblock_261': 'xxx_mobilecollapsblock_261',
        'mobilecollapsblockheader_262': 'xxx_mobilecollapsblockheader_262',
        'mobilecollapsblockcontent_263': 'xxx_mobilecollapsblockcontent_263',
        'mobilelabel_264': 'xxx_mobilelabel_264',
        'mobilecollapsblock_265': 'xxx_mobilecollapsblock_265',
        'mobilecollapsblockheader_266': 'xxx_mobilecollapsblockheader_266',
        'mobilecollapsblockcontent_267': 'xxx_mobilecollapsblockcontent_267',
        'mobilelabel_268': 'xxx_mobilelabel_268',
        'mobilelabel_269': 'xxx_mobilelabel_269',
        'mobilelabel_270': 'xxx_mobilelabel_270',
        'mobilelabel_271': 'xxx_mobilelabel_271',
        'mobilelabel_272': 'xxx_mobilelabel_272',
        'mobilelabel_273': 'xxx_mobilelabel_273',
        'mobilelabel_274': 'xxx_mobilelabel_274',
        'mobilelabel_275': 'xxx_mobilelabel_275',
        'mobilelabel_276': 'xxx_mobilelabel_276',
        'mobilelabel_277': 'xxx_mobilelabel_277',
        'mobilecollapsblock_278': 'xxx_mobilecollapsblock_278',
        'mobilecollapsblockheader_279': 'xxx_mobilecollapsblockheader_279',
        'mobilecollapsblockcontent_280': 'xxx_mobilecollapsblockcontent_280',
        'mobilelabel_281': 'xxx_mobilelabel_281',
        'mobilelabel_282': 'xxx_mobilelabel_282',
        'mobilelabel_283': 'xxx_mobilelabel_283',
        'mobilelabel_284': 'xxx_mobilelabel_284',
        'mobilelabel_285': 'xxx_mobilelabel_285',
        'mobilelabel_286': 'xxx_mobilelabel_286',
        'mobilelabel_287': 'xxx_mobilelabel_287',
        'mobilecollapsblock_288': 'xxx_mobilecollapsblock_288',
        'mobilecollapsblockheader_289': 'xxx_mobilecollapsblockheader_289',
        'mobilecollapsblockcontent_290': 'xxx_mobilecollapsblockcontent_290',
        'mobilelabel_291': 'xxx_mobilelabel_291',
        'mobilelabel_292': 'xxx_mobilelabel_292',
        'mobilelabel_293': 'xxx_mobilelabel_293',
        'mobilelabel_294': 'xxx_mobilelabel_294',
        'mobilelabel_295': 'xxx_mobilelabel_295',
        'mobilelabel_296': 'xxx_mobilelabel_296',
        'mobilelabel_297': 'xxx_mobilelabel_297',
        'mobilelabel_298': 'xxx_mobilelabel_298',
        'mobilelabel_299': 'xxx_mobilelabel_299',
        'mobilelabel_300': 'xxx_mobilelabel_300',
        'mobilelabel_301': 'xxx_mobilelabel_301',
        'mobilelabel_302': 'xxx_mobilelabel_302',
        'mobilelabel_303': 'xxx_mobilelabel_303',
        'mobilecollapsblock_304': 'xxx_mobilecollapsblock_304',
        'mobilecollapsblockheader_305': 'xxx_mobilecollapsblockheader_305',
        'mobilecollapsblockcontent_306': 'xxx_mobilecollapsblockcontent_306',
        'mobilelabel_307': 'xxx_mobilelabel_307',
        'mobilecollapsblock_308': 'xxx_mobilecollapsblock_308',
        'mobilecollapsblockheader_309': 'xxx_mobilecollapsblockheader_309',
        'mobilecollapsblockcontent_310': 'xxx_mobilecollapsblockcontent_310',
        'mobilelabel_311': 'xxx_mobilelabel_311',
        'mobilelabel_312': 'xxx_mobilelabel_312',
        'mobilelabel_313': 'xxx_mobilelabel_313',
        'mobilelabel_314': 'xxx_mobilelabel_314',
        'mobilelabel_315': 'xxx_mobilelabel_315',
        'mobilelabel_316': 'xxx_mobilelabel_316',
        'mobilelabel_317': 'xxx_mobilelabel_317',
        'mobilelabel_318': 'xxx_mobilelabel_318',
        'mobilecollapsblock_319': 'xxx_mobilecollapsblock_319',
        'mobilecollapsblockheader_320': 'xxx_mobilecollapsblockheader_320',
        'mobilecollapsblockcontent_321': 'xxx_mobilecollapsblockcontent_321',
        'mobilelabel_322': 'xxx_mobilelabel_322',
        'mobilelabel_323': 'xxx_mobilelabel_323',
        'mobilelabel_324': 'xxx_mobilelabel_324',
        'mobilelabel_325': 'xxx_mobilelabel_325',
        'mobilelabel_326': 'xxx_mobilelabel_326',
        'mobilelabel_327': 'xxx_mobilelabel_327',
        'mobilelabel_328': 'xxx_mobilelabel_328',
        'mobilecollapsblock_329': 'xxx_mobilecollapsblock_329',
        'mobilecollapsblockheader_330': 'xxx_mobilecollapsblockheader_330',
        'mobilecollapsblockcontent_331': 'xxx_mobilecollapsblockcontent_331',
        'mobilelabel_332': 'xxx_mobilelabel_332',
        'mobilelabel_333': 'xxx_mobilelabel_333',
        'mobilelabel_334': 'xxx_mobilelabel_334',
        'mobilelabel_335': 'xxx_mobilelabel_335',
        'mobilelabel_336': 'xxx_mobilelabel_336',
        'mobilelabel_337': 'xxx_mobilelabel_337',
        'mobilelabel_338': 'xxx_mobilelabel_338',
        'mobilelabel_339': 'xxx_mobilelabel_339',
        'mobilelabel_340': 'xxx_mobilelabel_340'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fix for jQuery Mobile's footer in Cordova webview on WP8 devices
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
        document.createTextNode("@media screen and (orientation: portrait){@-ms-viewport {width: 320px; height: 534px;user-zoom: fixed;zoom: 1;}}" + "@media screen and (orientation:landscape){@-ms-viewport{width:480px;user-zoom:fixed;zoom:1;}}"));
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }

    Apperyio.CurrentScreen = 'xxx';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    var xxx_beforeshow = function() {
            Apperyio.CurrentScreen = "xxx";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var xxx_onLoad = function() {
            xxx_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            xxx_deviceEvents();
            xxx_windowEvents();
            xxx_elementsEvents();
        };

    // screen window events
    var xxx_windowEvents = function() {

            $('#xxx').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var xxx_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var xxx_elementsExtraJS = function() {
            // screen (xxx) extra code

            /* CustomComponent1_341_mobilecollapsblock_219 */

            $("#xxx_CustomComponent1_341_mobilecollapsblock_219 .ui-collapsible-heading-toggle").attr("tabindex", "16");

            /* CustomComponent1_341_mobilecollapsblock_224 */

            $("#xxx_CustomComponent1_341_mobilecollapsblock_224 .ui-collapsible-heading-toggle").attr("tabindex", "17");

            /* CustomComponent1_341_mobilecollapsblock_237 */

            $("#xxx_CustomComponent1_341_mobilecollapsblock_237 .ui-collapsible-heading-toggle").attr("tabindex", "18");

            /* CustomComponent1_341_mobilecollapsblock_250 */

            $("#xxx_CustomComponent1_341_mobilecollapsblock_250 .ui-collapsible-heading-toggle").attr("tabindex", "19");

            /* mobilecollapsblock_261 */

            $("#xxx_mobilecollapsblock_261 .ui-collapsible-heading-toggle").attr("tabindex", "20");

            /* mobilecollapsblock_265 */

            $("#xxx_mobilecollapsblock_265 .ui-collapsible-heading-toggle").attr("tabindex", "21");

            /* mobilecollapsblock_278 */

            $("#xxx_mobilecollapsblock_278 .ui-collapsible-heading-toggle").attr("tabindex", "22");

            /* mobilecollapsblock_288 */

            $("#xxx_mobilecollapsblock_288 .ui-collapsible-heading-toggle").attr("tabindex", "23");

            /* mobilecollapsblock_304 */

            $("#xxx_mobilecollapsblock_304 .ui-collapsible-heading-toggle").attr("tabindex", "24");

            /* mobilecollapsblock_308 */

            $("#xxx_mobilecollapsblock_308 .ui-collapsible-heading-toggle").attr("tabindex", "25");

            /* mobilecollapsblock_319 */

            $("#xxx_mobilecollapsblock_319 .ui-collapsible-heading-toggle").attr("tabindex", "26");

            /* mobilecollapsblock_329 */

            $("#xxx_mobilecollapsblock_329 .ui-collapsible-heading-toggle").attr("tabindex", "27");

        };

    // screen elements handler
    var xxx_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

        };

    $(document).off("pagebeforeshow", "#xxx").on("pagebeforeshow", "#xxx", function(event, ui) {
        xxx_beforeshow();
    });

    if (runBeforeShow) {
        xxx_beforeshow();
    } else {
        xxx_onLoad();
    }
};

$(document).off("pagecreate", "#xxx").on("pagecreate", "#xxx", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    xxx_js();
});